### ISSUE TITLE
About supporting short/unsigned short of the test/wait routines

### ISSUE THREAD

**Issue by lyu** [openshmem-org/tests-sos#19]
According to version 1.5 of the spec, `short` and `unsigned short` are not supported by any of the test/wait routines. Should they be removed form the unit tests?

**Comment by davidozog** [comment]
@lyu  Well... those routines are deprecated, but that doesn't mean they are completely unsupported...  In fact, the spec says they **must** be supported until indicated otherwise.  Are you requesting they be removed?

I see these types in `test/unit/cxx_test_shmem_wait_until.cpp` - are there any other instances you know of?  Thanks.

**Comment by lyu** [comment]
`c11_shmem_wait_until_all_any_some.c` and `c11_test_shmem_wait_until.c` also have those.

But you are right! I missed Annex F completely. Closing.
